name: mkr2

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: project_gallery.settings
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 'False'
        run: |
          python manage.py test

      - name: Run migrations
        run: python manage.py migrate

      - name: Run migrations (check only)
        env:
          DJANGO_SETTINGS_MODULE: project_gallery.settings
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 'False'
        run: |
          python manage.py migrate --check

      - name: Collect static files (noinput)
        env:
          DJANGO_SETTINGS_MODULE: project_gallery.settings
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: 'False'
        run: |
          python manage.py collectstatic --noinput
